robotis_op3:
  # Publish all joint states -----------------------------------

  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  head_pan_position:
    type: effort_controllers/JointPositionController
    joint: head_pan
    pid: {p: 50.0, i: 1.0, d: 10.0}

  head_tilt_position:
    type: effort_controllers/JointPositionController
    joint: head_tilt
    pid: {p: 50.0, i: 1.0, d: 10.0}

  head_pan_velocity:
    type: effort_controllers/JointVelocityController
    joint: head_pan
    pid: {p: 50.0, i: 1.0, d: 10.0}

  head_tilt_velocity:
    type: effort_controllers/JointVelocityController
    joint: head_tilt
    pid: {p: 50.0, i: 1.0, d: 10.0}

  # wheel_left_joint_vel:
  #   type: velocity_controllers/JointVelocityController
  #   joint: wheel_left_joint
  #
  # wheel_right_joint_vel:
  #   type: velocity_controllers/JointVelocityController
  #   joint: wheel_right_joint

  # gains:
     # wheel_right_joint: {p: 30,  d: 0, i: 0, i_clamp: 1.}
     # wheel_left_joint: {p: 30,  d: 0, i: 0, i_clamp: 1.0}
