kobuki:
  wheel_left_joint_vel:
    type: velocity_controllers/JointVelocityController
    joint: wheel_left_joint
    pid: {p: 50.0, i: 1.0, d: 10.0}


  wheel_right_joint_vel:
    type: velocity_controllers/JointVelocityController
    joint: wheel_right_joint
    pid: {p: 50.0, i: 1.0, d: 10.0}

  # gazebo_ros_control:
  #   pid_gains:
  #     wheel_right_joint:
  #       p: 30.0
  #       i: 0.0
  #       d: 0.0
  #
  #       wheel_left_joint:
  #       p: 30.0
  #       i: 0.0
  #       d: 0.0
